import { memberData } from '../../lib/member.js';
const encoder=new TextEncoder();
function json(value,status=200,headers={}){return new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}})}
function err(message,status=400){return json({error:message},status)}
function hex(buf){return Array.from(new Uint8Array(buf),b=>b.toString(16).padStart(2,'0')).join('')}
async function sha(value){return hex(await crypto.subtle.digest('SHA-256',encoder.encode(value)))}
function randomHex(n){return hex(crypto.getRandomValues(new Uint8Array(n)))}
async function hashPassword(pass,salt){const material=await crypto.subtle.importKey('raw',encoder.encode(pass),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:encoder.encode(salt),iterations:210000,hash:'SHA-256'},material,256))}
function equal(a,b){if(typeof a!=='string'||typeof b!=='string')return false;const x=encoder.encode(a),y=encoder.encode(b);let diff=x.length^y.length;for(let i=0;i<Math.max(x.length,y.length);i++)diff|=(x[i]||0)^(y[i]||0);return diff===0}
function cookie(name,request){return (request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)||''}
function sessionCookie(token,maxAge){return 'sk_session='+token+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age='+maxAge}
async function session(ctx){const token=cookie('sk_session',ctx.request);if(!/^[0-9a-f]{64}$/.test(token))return null;return ctx.env.DB.prepare('SELECT username,role FROM sessions WHERE token_hash=? AND expires_at>?').bind(await sha(token),Date.now()).first()}
async function body(req){try{return await req.json()}catch{return {}}}
function originOK(req){const o=req.headers.get('Origin');return !o||o===new URL(req.url).origin}
async function bootstrap(env){if(!env.DEFAULT_USER_PASSWORD)return;const setting=await env.DB.prepare("SELECT value FROM settings WHERE key='default_user_initialized'").first();if(setting)return;const salt=randomHex(16),hash=await hashPassword(env.DEFAULT_USER_PASSWORD,salt);await env.DB.batch([env.DB.prepare('INSERT OR IGNORE INTO users(username,salt,password_hash,created_at) VALUES(?,?,?,?)').bind('seelenkraft',salt,hash,Date.now()),env.DB.prepare("INSERT OR IGNORE INTO settings(key,value) VALUES('default_user_initialized','1')")])}
async function login(ctx){const env=ctx.env;if(!env.ADMIN_PASSWORD||!env.DB)return err('Server ist noch nicht eingerichtet. D1 und ADMIN_PASSWORD konfigurieren.',503);const b=await body(ctx.request),username=String(b.username||'').trim(),password=String(b.password||'');if(!/^[A-Za-z0-9._-]{3,32}$/.test(username)||!password||password.length>128)return err('Ungültige Zugangsdaten.',401);const ip=ctx.request.headers.get('CF-Connecting-IP')||'unknown',key=await sha(ip+'|'+username.toLowerCase());const now=Date.now(),attempt=await env.DB.prepare('SELECT failures,expires_at FROM login_attempts WHERE key=?').bind(key).first();if(attempt&&attempt.expires_at>now&&attempt.failures>=5)return err('Zu viele Versuche. Bitte später erneut anmelden.',429);await bootstrap(env);let role=null;if(username.toLowerCase()==='admin'&&equal(password,env.ADMIN_PASSWORD))role='admin';else if(username.toLowerCase()!=='admin'){const user=await env.DB.prepare('SELECT username,salt,password_hash FROM users WHERE username=?').bind(username).first();if(user&&equal(await hashPassword(password,user.salt),user.password_hash))role='member'}if(!role){await env.DB.prepare('INSERT INTO login_attempts(key,failures,expires_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET failures=CASE WHEN expires_at<? THEN 1 ELSE failures+1 END,expires_at=?').bind(key,1,now+900000,now,now+900000).run();return err('Anmeldung fehlgeschlagen. Bitte Zugangsdaten prüfen.',401)}await env.DB.prepare('DELETE FROM login_attempts WHERE key=?').bind(key).run();const token=randomHex(32);await env.DB.prepare('INSERT INTO sessions(token_hash,username,role,expires_at) VALUES(?,?,?,?)').bind(await sha(token),role==='admin'?'admin':username,role,now+7*86400000).run();return json({ok:true,role},200,{'Set-Cookie':sessionCookie(token,604800)})}
async function adminUsers(ctx,s){if(!s||s.role!=='admin')return err('Nur für Administratoren.',403);const db=ctx.env.DB,method=ctx.request.method;if(method==='GET'){const rows=await db.prepare('SELECT username,created_at FROM users ORDER BY username').all();return json({users:[{username:'admin',created_at:null},...(rows.results||[])]})}const b=await body(ctx.request),username=String(b.username||'').trim();if(!/^[A-Za-z0-9._-]{3,32}$/.test(username)||username.toLowerCase()==='admin')return err('Benutzername ungültig oder reserviert.');if(method==='DELETE'){const result=await db.prepare('DELETE FROM users WHERE username=?').bind(username).run();if(!result.meta.changes)return err('Nutzer nicht gefunden.',404);await db.prepare('DELETE FROM sessions WHERE username=?').bind(username).run();return json({ok:true})}const password=String(b.password||'');if(password.length<10||password.length>128)return err('Passwort muss 10 bis 128 Zeichen lang sein.');const salt=randomHex(16),hash=await hashPassword(password,salt);if(method==='POST'){try{await db.prepare('INSERT INTO users(username,salt,password_hash,created_at) VALUES(?,?,?,?)').bind(username,salt,hash,Date.now()).run()}catch{return err('Dieser Benutzername existiert bereits.',409)}return json({ok:true},201)}if(method==='PUT'){const result=await db.prepare('UPDATE users SET salt=?,password_hash=? WHERE username=?').bind(salt,hash,username).run();if(!result.meta.changes)return err('Nutzer nicht gefunden.',404);await db.prepare('DELETE FROM sessions WHERE username=?').bind(username).run();return json({ok:true})}return err('Methode nicht erlaubt.',405)}
export async function onRequest(ctx){const req=ctx.request,url=new URL(req.url),route=url.pathname.replace(/\/$/,'');if(!ctx.env.DB)return err('D1-Bindung DB fehlt.',503);if(!['GET','POST','PUT','DELETE'].includes(req.method))return err('Methode nicht erlaubt.',405);if(req.method!=='GET'&&!originOK(req))return err('Ungültiger Ursprung.',403);try{if(route==='/api/login'&&req.method==='POST')return await login(ctx);const s=await session(ctx);if(route==='/api/me'&&req.method==='GET')return json(s?{authenticated:true,role:s.role,username:s.username}:{authenticated:false});if(route==='/api/logout'&&req.method==='POST'){if(s)await ctx.env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha(cookie('sk_session',req))).run();return json({ok:true},200,{'Set-Cookie':sessionCookie('',0)})}if(route==='/api/member'&&req.method==='GET')return s?json({...memberData,role:s.role}):err('Bitte anmelden.',401);if(route==='/api/admin/users')return await adminUsers(ctx,s);return err('Nicht gefunden.',404)}catch(e){console.error('API error',e);return err('Serverfehler. Bitte D1-Migration und Konfiguration prüfen.',500)}}
